
DEP_DIR := extern-dependencies/

.PHONY: help
help:
	@echo "Please choose one of the targets:"
	@echo "submodule          init and update all the submodules."

.PHONY: submodule
submodule:
	git submodule init
	git submodule update

